version: '3.7'
services:
  docker-docsify:
    container_name: docsify
    image: littlstar/docker-docsify
    ports:
      - '3000:3000'
    restart: always
    volumes:
        - './docs:/usr/local/docsify'

  frontend_react:
    container_name: frontend_react
    image: node:13.12.0-alpine
    working_dir: /app
    volumes:
      - ./frontend_react:/app
      - /app/node_modules
    ports:
      - '8081:3000'
    depends_on:
      - rest-api
    command: "npm start"
    restart: always
    env_file: .env
    # Needed for compose 
    stdin_open: true

  rest-api:
    container_name: rest-api
    image: golang:1.14
    working_dir: /go/src/app
    ports:
      - 8082:8080
    depends_on:
      - 'mongo'
    volumes:
      - ./rest_golang:/go/src/app
    command: go run main.go
    restart: always
    env_file: .env

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local

