version: "3.7"
services:
  frontend_react:
    container_name: frontend_react
    image: node:13.12.0-alpine
    working_dir: /app
    volumes:
      - ./frontend_react:/app
      - /app/node_modules
    ports:
      - "8081:3000"
    depends_on:
      - rest_api
    command: "npm start"
    restart: always
    env_file: .env
    # Needed for compose
    stdin_open: true

  rest_api:
    container_name: rest_api
    image: golang:1.17
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - "mongo"
    volumes:
      - ./rest_golang:/go/src/app
    command: go run main.go
    restart: always
    env_file: .env

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
