version: '3.7'
services:
  docker-docsify:
    image: littlstar/docker-docsify
    ports:
      - '3000:3000'
    restart: always
    volumes:
        - './docs:/usr/local/docsify'

  frontend_react:
    image: node:13.12.0-alpine
    working_dir: /app
    volumes:
      - ./frontend_react:/app
      - /app/node_modules
    ports:
      - '8081:3000'
    command: "npm start"
    restart: always
    env_file: .env
    # Needed for compose 
    stdin_open: true
    networks:
      mindfuel_activity:
        ipv4_address: 10.10.10.1

  rest-api:
    image: golang:1.14
    working_dir: /go/src/app
    ports:
      - 8082:8080
    volumes:
      - ./rest_golang:/go/src/app
    command: go run main.go
    restart: always
    env_file: .env
    networks:
      mindfuel_activity:
        ipv4_address: 10.10.10.2

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local

networks:
    mindfuel_activity:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16
